version: "3.8"

services:
  fast-api-service:
    build:
      context: .
      dockerfile: FastAPI.Dockerfile
    volumes:
      - /var/log/rag_service/log/:/var/log/
    ports:
      - "8031:80"
    env_file:
      - .env
