version: "3.8"

services:
  fast-api-service:
    build:
      context: .
      dockerfile: FastAPI.Dockerfile
    volumes:
      - ~/rag_serice/log/:/var/log/
    ports:
      - "8031:8000"
    env_file:
      - .env
